WIP: allow colors to be specified by hex code
ethanmdavidson/DeathProgress pull request #16
Opened 2024-01-04 03:22 UTC by howeyc

This my attempt to fix #15 

It's not quite there, as the color box in the settings screen does not update unless the dialog box is opened. But the dialog box does open with the value set by the hex edit box.

Is there a way to "refresh" or redraw the settings screen after a change? I'm tempted to load in the color picker lib (I don't actually know how to do this, but I'm up for attempting it), and add a "Redraw" method for the box.

Please review whenever you have a chance, thanks.

2024-01-06 15:57 UTC, ethanmdavidson commented
Hey @howeyc thanks for the contribution! I'm not sure how to refresh/redraw the preference screen, sorry. 

As for loading in the colorpicker lib, that is something I've done before, but I don't totally recall how I did it. I think maybe something like this:
1. clone [colorpickerpreference](https://github.com/skydoves/colorpickerpreference) to your local machine
2. add `mavenLocal()` to the [repository config in the build script](https://github.com/ethanmdavidson/DeathProgress/blob/main/build.gradle.kts#L4) (put it before `google()` and `mavenCentral()` so that it will be searched first)
3. make changes to colorpickerpreference, and then build it and publish to mavenLocal (I think there's a `publishToMavenLocal` gradle task that does this)
4. Change [the dependency on colorpickerpreference](https://github.com/ethanmdavidson/DeathProgress/blob/main/app/build.gradle.kts#L58) to reference the version that you just published (I think it's currently [2.0.7-SNAPSHOT](https://github.com/skydoves/ColorPickerPreference/blob/master/gradle.properties#L34))
5. Build the wallpaper app and run it on your connected device or emulator to test your changes.

I *think* this is the process I used last time. It's very cumbersome, and there's probably a better way. You might be able to just check out both projects, and then change the app's colorpickerpreference dependency to [reference the locally checked out project instead of the artifact from the registry](https://stackoverflow.com/questions/35606790/how-to-add-a-dependency-to-another-project-properly-using-gradle)? Or, I think there's [an example app in the colorpickerpreference repo itself](https://github.com/skydoves/ColorPickerPreference/tree/master/app), so you might be able to do all your development in the colorpickerpreference repo, then open a PR, and after a new release is made with your changes, update the wallpaper app to use the new version.

Sorry I can't be more helpful. It's been a while since I worked on this project much and I don't remember many of the details.

2024-01-07 13:30 UTC, howeyc commented
I figured it out, let me know what you think.

2024-01-08 13:37 UTC, ethanmdavidson commented
Awesome, hopefully sometime this week I'll take a look and make a beta release. I'll keep you posted

2024-01-15 18:07 UTC, ethanmdavidson requested changes
The code looks good, and it works well! Just needs a little error handling.

2024-01-15 18:07 UTC, ethanmdavidson commented on app/src/main/kotlin/com/machinerychorus/lifeprogresswallpaper/WallpaperSettingsFragment.kt
> +			manager.setColor(getString(R.string.bgColorKey), Color.parseColor(newValue.toString()))
You need to add a try+catch around `Color.parseColor`, or else the app will crash when the input can't be parsed as a color. Stacktrace: 
<details>

```
java.lang.IllegalArgumentException: Unknown color
    at android.graphics.Color.parseColor(Color.java:1391)
    at com.machinerychorus.lifeprogresswallpaper.WallpaperSettingsFragment.onCreatePreferences$lambda$3(WallpaperSettingsFragment.kt:38)
    at com.machinerychorus.lifeprogresswallpaper.WallpaperSettingsFragment.$r8$lambda$Unk1E1zNiavyZJLz4QMWb0D3Y80(Unknown Source:0)
    at com.machinerychorus.lifeprogresswallpaper.WallpaperSettingsFragment$$ExternalSyntheticLambda2.onPreferenceChange(Unknown Source:6)
    at androidx.preference.Preference.callChangeListener(Preference.java:1131)
    at androidx.preference.EditTextPreferenceDialogFragmentCompat.onDialogClosed(EditTextPreferenceDialogFragmentCompat.java:149)
    at androidx.preference.PreferenceDialogFragmentCompat.onDismiss(PreferenceDialogFragmentCompat.java:291)
    at androidx.fragment.app.DialogFragment$3.onDismiss(DialogFragment.java:132)
    at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1393)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6669)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

</details>

The minimum here IMO is to put a try+catch around the parse call, and pop up a toast to alert the user if there's an error. Check out [IntegerPreference,setText](https://github.com/ethanmdavidson/DeathProgress/blob/main/app/src/main/kotlin/com/machinerychorus/lifeprogresswallpaper/customPrefs/IntegerPreference.kt#L21) for an example.

2024-01-15 18:07 UTC, ethanmdavidson commented on app/src/main/kotlin/com/machinerychorus/lifeprogresswallpaper/WallpaperSettingsFragment.kt
> +			manager.setColor(getString(R.string.fgColorKey), Color.parseColor(newValue.toString()))
try+catch needed here as well

2024-01-15 22:50 UTC, howeyc commented
I made a change to pop up a toast on invalid hex color

2024-01-17 03:08 UTC, ethanmdavidson approved these changes
Nice! Thank you again for your contribution. I'll cut a release sometime soon; might have to do a bit of housekeeping first to get all my sdk versions and stuff in order

2024-01-17 03:09 UTC, merged

2024-01-20 17:19 UTC, ethanmdavidson commented
Hey @howeyc! just wanted to let you know that I've built a new release and submitted it for review. Once it passes review, it'll be available in the open beta for a little while (probably 2 weeks) and then if everything looks good I'll promote it to production. If you like, you can join the open beta here: https://play.google.com/apps/testing/com.machinerychorus.lifeprogresswallpaper